- repo: https://github.com/Calinou/pre-commit-luacheck
  rev: v1.0.0
  hooks:
    - id: luacheck
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: pretty-format-json
      args:
        - --autofix
        - --no-sort-keys
